name: Run Unit Tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env: GITHUB_WORKSPACE/
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.6
          
      - name: Create a virtual environment
        run: python3 -m venv genieparser_venv
        
      - name: Activate the virtual environment
        run: source genieparser_venv/bin/activate
        
      - name: Check virtualenv
        run: pip -V
        
      - name: Install pyATS
        run: pip install pyats
      - name: Install Genie
        run: pip install genie

      - name: Prepare repo
        uses: actions/checkout@master
        
      - name: Check virtualenv
        run: pip -V
        
      - name: Run Test
        uses: xiaoxinz-cisco/pyats_run_tests@master
        with:
#         current path is: github/workspace == this repository
          path: 'tests'
          deps_list: 'requirement'
